version: '3'

services:
  backend:
    build: ./number-plate-detector-api
    ports:
      - "8002:8002"
    volumes:
      - ./number-plate-detector-api/.env:/app/.env
    env_file:
      - ./number-plate-detector-api/.env
    environment:
      - PORT=8002
      # Add CORS allowed origins
      - CORS_ORIGINS=https://cc-project-frontend-107894419251.us-central1.run.app,http://localhost:3000,http://localhost:3003
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: ./number-plate-detector
    ports:
      - "3003:3003"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 